### ISSUE TITLE
SELinux instructions cause WiFi issues

### ISSUE THREAD

**Issue by tnixa** [appsody/website#401] opened 2019-11-19 21:32 UTC
**Describe the bug**
I followed the SELinux instructions below and whitelisted my home directory which caused my IBM wifi certificate to not work. We should change the instructions to not recommend whitelisting the home directory

https://appsody.dev/docs/getting-started/installation

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] IBM RHEL 7.7

**Comment by helenmasters** [comment] 2019-11-27 14:55
There is additional work to do in here, as part of the current instructions are not clear:

In our example we say if you are unsure about which directories are mounted by the stack you are using, you can inspect the output of the `run` command, and look at the `-v` parameters in the docker run command.

We then show a whole set of parameters being passed to run via -v and then make the statement "In the example above, there is one binding mount:"

It is unclear how we have come to the conclusion that there is only one binding mount in the example (I have a feeling that it's probably '/project/user-app' (our failing case in the example above) and the other folders listed are within the home directory but we've not made that clear).

Note, I was going to try and make this fix in the docs but I have a feeling that you'll have to change all the examples (if you're going to say don't whitelist the home directory) so that the user doesn't install Appsody projects into the user's home directory and I don't have access to SELinux to get sample output.

**Comment by chilanti** [comment] 2019-12-02 16:46
@helenmasters - I discussed this issue with @tnixa. I think we should drop the text from the point where it says: 
>
>  In general - however - you should be required to run the command at most twice:
>
to the end of the section. I agree it's confusing.
We should replace all that with a single sentence that says something like:
> We recommend you create a `projects` folder under your home directory - to host all of your future Appsody projects - and that you white-list that directory. 
>
The problem I see here is that some stacks (the Java-based stacks) also mount the `~/.m2` directory - we should call that out, because for those stacks that directory also needs to be whitelisted. Thoughts?

**Comment by tnixa** [comment] 2019-12-03 14:35
I've reinstalled my machine and I'll be working with @chilanti on recreating this issue today.

**Comment by helenmasters** [comment] 2019-12-03 14:50
@tnixa @chilanti I spoke with @doveye in the content team today about my idea to put these details into a FAQ and the main concern was that these are Troubleshooting not FAQ (but we don't currently have a Troubleshooting section within the docs). In addition, we don't want to maintain SELinux specific instructions in case anything changes under us.

So I'm investigating whether we can link out to SELinux docs to cover the basic issue instead (if we can find a link with enough detail in it to do that), we could then add a link to that doc from the Ubuntu and RHEL install pages (which I'm creating). It wouldn't stop us calling out the `projects` folder specifically, and stating that there may be issues with folders specific to other stacks (e.g. the Java-based stacks).

**Comment by chilanti** [comment] 2019-12-04 21:16
We haven't been able to reproduce the problem (i.e. Appsody - or Docker, for what matters - failing to function on SELinux). Things just work - we tried numerous times with fresh installs of RHEL 7.7, SELinux enabled and enforcing (clearly - with no special SELinux policies, just the out of the box scenario).  At this point, I am wondering whether we should even maintain a detailed discussion on what to do if someone is working on a system with SELinux turned on, and has special policies that prevent Docker from working. Would it be acceptable to just show the symptom (which we couldn't reproduce) and then point to the Docker docs that talk about SELinux? We should definitely refrain from recommending to white list the home dir.

**Comment by helenmasters** [comment] 2019-12-16 10:38
Assigning to myself as part of refining and documenting the Installation pages for on all platforms under #375 as I need to make sure that we don't whitelist the home dir as per the current installation pages.

**Comment by helenmasters** [comment] 2020-02-26 10:22
Closing, as I've reworked this and added the text we decided that we needed to keep to the FAQ.

**Closed by helenmasters** 2020-02-26 10:22 UTC
Labels: documentation
