### ISSUE TITLE
Clarify the APPSODY_PREP is not run before ON_CHANGE events

### ISSUE THREAD

**Issue by henrynash** [appsody/website#262] opened 2019-09-19 23:13 UTC
Our current docs (on stack variables) for APPSODY_PREP starts with:

`This is an optional command executed before the APPSODY_RUN/TEST/DEBUG and APPSODY_RUN/TEST/DEBUG_ON_CHANGE commands are run. 
`

This is somewhat confusing, and implies that APPSODY_PREP is run before each CHANGE event - which is not the case. It is only run on APPSODY_RUN/TEST/DEBUG.

**Comment by kylegc** [comment] 2019-09-20 20:51
Duplicate of #268

**Closed by kylegc** 2019-09-20 20:51 UTC
Labels: duplicate
