### ISSUE TITLE
Search doesn't work for two words with a space inbetween

### ISSUE THREAD

**Issue by helenmasters** [appsody/website#305] opened 2019-10-17 13:29 UTC
**Describe the bug**
I was searching for references to "watch directories" within the website and the search returned multiple references including the 'CLI reference' page. When I used CTRL-F to search within that page explicitly there were no references to "watch directories" so I expect we're searching for "watch" under the covers.

**To Reproduce**
1. Go to 'appsody.dev'
2. Click on 'Search'
3. Search for "watch directories"
4. Search for hits for that text string within the CLI Reference page using Ctrl-F

**Expected behavior**
Only given a list of pages with matches to "watch directories" ie matching the entire string not just the first word.

**Actual behaviour**
Given a list of pages with matches to "watch" in (I think!).

**Additional context**
N/A

**Comment by kilnerm** [comment] 2019-10-18 09:12
From my perspective I would like to see some kind of indication as to which of the search terms I have entered are present in each result returned.

This saves time looking through search results that do not contain all my search terms or sets an expectation of what I will find if I do choose to look at them, thereby reducing frustration at being presented results that do not match my whole search term.

**Comment by KyeMaloy97** [comment] 2019-10-22 13:29
The results are currently ranked, the first one is a "best match" so say you searched for "watch directories", the first result is one that contains both words, in sequence. The second result either has the same sequence or it has the words repeated a lot inside the doc. This continues down the list until the last results, which probably has one instance of each word in the doc somewhere, not necessarily in sequence.

The Search library we are use is called jsSearch and it does have some limitations to what it can do, as far as we can tell. Lots of other sites use a plugin called Angolia which allows you to specify the stuff you wanna prioritise, etc but they cost money past their free tiers (which we may or may not exceed, hard to tell). jsSearch, for instance, does not let us go to that particular area of the part when you click a result.

Interested to see others opinions on this though. If we want a more robust search, we may need to look at stripping out jsSearch and moving to a different plugin.

**Comment by helenmasters** [comment] 2019-10-24 10:03
Looking at the results, the first results was the "Appsody Environment Variables" page which had one hit for "watch directories".

I was confused because of two things:
 - 1. The search also returned the "CLI Reference" page as  the second hit. However this page does not include the phrase "watch directories" in it... but as I was only interested in that page originally I thought that the search was broken.

- 2. As there is no highlighting of the search result so I had to then use Ctrl-F to find the result.

I also like @kilnerm's suggestion.

If we do end up looking for a more robust search plugin my ideal would also highlight the matching terms in some way so that I don't need to use Ctrl-F once on the page to actually find the search results.

**Comment by ddunn2** [comment] 2019-10-24 14:44
@neeraj-laad @helenmasters We can't do matching & non-matching terms. When you search `watch directories` for example, all of the results contain both words. So there is no concept of 'non-matching' terms. 

As Kye mentioned above, `js-search` will prioritise results that have your search term in sequence but will match to any result that contains both words. The reason the "CLI Reference" page was the second hit, is because it contains many instances of both `watch` & `directories` but as separate terms. 

As for the highlighting matched terms, I don't even think Google does that when you jump to a page. I certainly haven't been able to find any examples of that. 

If anything this shows us where we may have holes in our documentation, if you're searching for `watch directories` and not getting the results you expect then why is that? And how can we improve the documentation so the results are fitting. Searching `watch directories` showed us that in our documentation we only have one result that actually mentions `watch directories` as a phrase. If it is a term that is important or that people would search then we need to ensure there is adequate documentation for it. 

We are using a free search plugin, and with that there will sadly be limitations but I feel the search is working as we'd expect. I hope this helps :)

**Comment by neeraj-laad** [comment] 2019-10-29 14:02
@ddunn2 Thanks for your update. I've seen lots of websites do matching and non-matching terms but that will be a separate issue if we want to go after it. 

As part of this issue, I think we need to show users results that match the entire search string first so users like @helenmasters wont be confused with the results. 

Search string: "watch directories" 

Results matching "watch directories"
result matching "watch" and "directories"
results matching "watch" or "directories"

Is this already our current implementation or can we somehow make this happen?

**Comment by KyeMaloy97** [comment] 2019-10-29 14:34
@neeraj-laad  The current implementation always shows the best result at the top as far as I can tell, so the first result in the list will be the closest. Then as you go down the list the results get more fuzzy, until the bottom of the results are matching on one word or the other.

**Comment by ddunn2** [comment] 2019-10-30 11:33
@neeraj-laad I've also seen a lot of websites that do matching and non-matching terms but the plugin Appsody uses doesn't seem to return non-matching terms, so we couldn't highlight those. 

Currently the plugin works as follows: 
Search results (in order)
Results matching "watch directories"
result matching "watch" and "directories"

As such I'm closing this issue, as I feel the search is working as intended, thanks everyone for your input :)

**Closed by ddunn2** 2019-10-30 11:33 UTC
